/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/AdminPanel': RouteRecordInfo<'/AdminPanel', '/AdminPanel', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Introduce': RouteRecordInfo<'/Introduce', '/Introduce', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/NotificationCenter': RouteRecordInfo<'/NotificationCenter', '/NotificationCenter', Record<never, never>, Record<never, never>>,
    '/Status': RouteRecordInfo<'/Status', '/Status', Record<never, never>, Record<never, never>>,
    '/SubmitApplication': RouteRecordInfo<'/SubmitApplication', '/SubmitApplication', Record<never, never>, Record<never, never>>,
    '/SubmitResponse': RouteRecordInfo<'/SubmitResponse', '/SubmitResponse', Record<never, never>, Record<never, never>>,
  }
}
